<?php

/**
 * @file
 * Promotion Block hooks and functions.
 */

use Drupal\promotion_block\PromotionBlockInterface;

/**
 * Check if cookie is set.
 */
function promotion_block_check_cookie() {
  $stack = \Drupal::service('request_stack');
  $cookie = $stack->getCurrentRequest()->cookies->get(PromotionBlockInterface::PROMOTION_BLOCK_COOKIE_NAME);
  return isset($cookie);
}

/**
 * Implements template_preprocess_page().
 */
function promotion_block_preprocess_page(&$variables) {
  $config = \Drupal::service('config.factory')->getEditable('promotion_block.settings');
  $is_front = \Drupal::service('path.matcher')->isFrontPage();

  // Load if enabled, frontpage and cookie.
  if ($is_front && !promotion_block_check_cookie() && $config->get('enable')) {
    $variables['#attached']['library'][] = 'promotion_block/promotion-block-load';
  }
}
